#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Export a markdown file using a latex header to a pdf"
    echo ""
    echo "usage: pdfexport <path/to/mdfile> <path/to/pdfout>"
    exit 1
fi


pandoc -N -s "$1" -o  "$2"  --highlight-style tango --include-in-header ~/Documents/projects/pdfexport/header.tex -V fontsize=11pt -V=subgraph --toc
